# Generated by Django 3.0.7 on 2020-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_qq_id', models.BigIntegerField()),
                ('qq_group_id', models.BigIntegerField()),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
    ]
